### ISSUE TITLE
why anchor test error on localnet

### ISSUE THREAD

**Issue by ThunderCross** [anoushk1234/metaplex-anchor-nft#6]
when run test script `mintNft` on  localnet:
https://github.com/anoushk1234/metaplex-anchor-nft/blob/27b17cb40670dc99bc78a3e775e5eb04184995b4/tests/metaplex-anchor-nft.ts#L99

there is an error:
```
 1) metaplex-anchor-nft
       Is initialized!:
     Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: instruction expected an executable account
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/src/connection.ts:4052:13)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at Connection.sendRawTransaction (node_modules/@solana/web3.js/src/connection.ts:4014:20)
      at sendAndConfirmRawTransaction (node_modules/@project-serum/anchor/src/provider.ts:284:21)
      at AnchorProvider.sendAndConfirm (node_modules/@project-serum/anchor/src/provider.ts:144:14)
      at MethodsBuilder.rpc [as _rpcFn] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:29:16)
```

And if I deploy to devnet, will cost 1.7sol : ` spend (1.78752984 SOL) + fee (0.00129 SOL)`

**Comment by ThunderCross** [comment]
补充一下，解决办法是在Anchor配置文件里，为本地网络补齐mpl_token_metadata程序

**Comment by ThunderCross** [comment]
To add, the solution is to fill the mpl_token_metadata program for the local network in the Anchor configuration file.

Anchor.toml
```
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/genesis/mpl_token_metadata@1.2.10.so"
```

you can download or build [mpl_token_metadata ](https://github.com/metaplex-foundation/metaplex-program-library/tree/master/token-metadata) for get .so file
