### ISSUE TITLE
Why test doesn't run on localnet?

### ISSUE THREAD

**Issue by torquedrop** [anoushk1234/metaplex-anchor-nft#7]
I tried to do test on local net.

But it's failed.
error output:
```
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: instruction expected an executable account
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/src/connection.ts:4480:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Connection.sendRawTransaction (node_modules/@solana/web3.js/src/connection.ts:4439:20)
      at sendAndConfirmRawTransaction (node_modules/@project-serum/anchor/src/provider.ts:284:21)
      at AnchorProvider.sendAndConfirm (node_modules/@project-serum/anchor/src/provider.ts:144:14)
      at MethodsBuilder.rpc [as _rpcFn] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:29:16)
```

And another questions:
1.Why you don't create associate token on contract?
2.Can I change this contract to do batch mint?

I'm beginner at solana. so I need you help now. Please give me a hand.

**Comment by anharu2394** [comment]
i have same issue

**Comment by torquedrop** [comment]
I think it doesn't run on localnet because TOKEN_METADATA_PROGRAM_ID.
I tried it on devnet and it runs correctly.
But I can't find that test signature on devnet solcsan.
What's the problem?

**Comment by anharu2394** [comment]
I've solved and passed the test.
You can check up Token metadata program id on localnet by using Solana explorer.
https://explorer.solana.com/address/metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s?cluster=devnet

Make sure token metadata program is correct.

**Comment by torquedrop** [comment]
I think it's just devent, not localnet? How do explorer localnet transaction?

**Comment by anharu2394** [comment]
You can set the Custom rpc url, so you can explorer on localnet.
![image](https://user-images.githubusercontent.com/26423094/180484597-1a93e6bd-243e-47fb-933c-2c3216f24fab.png)

**Comment by torquedrop** [comment]
Thanks @anharu2394

**Comment by anoushk1234** [comment]
You have to deploy the metaplex program on localnet for it to work, i used a tool called Amman that does that

**Comment by anoushk1234** [comment]
Look at how Metaplex has implemented it https://github.com/metaplex-foundation/js/blob/main/.ammanrc.js

**Comment by ThunderCross** [comment]
https://github.com/anoushk1234/metaplex-anchor-nft/issues/6#issuecomment-1231194670
